
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//

logic [2:0] q;

// add module here
counter_8 counter_81(
	.reset(~BTN[0]),
	.clk(BTN[1]),
	.q(q)
);

student_num sn1(
	.a(q),
	.num(LED[3:0]) //輸出
);


//*******************************//

endmodule
