
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//

//logic [3:0] H0,H1;

// add module here
hw_1114 hw_1114_1(
	.clk(BTN[0]),
	.reset(~BTN[2]),
	.w_q(LED[7:0])          //將結果存入變數
);

//seven_segment s0(
//	.A(H0),  		 //輸入
//	.y(HEX0)  //輸出
//);
//
//seven_segment s1(
//	.A(H1),  		 //輸入
//	.y(HEX1)  //輸出
//);
//
//*******************************//
endmodule
